//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Experience
    {
        public int ID { get; set; }
        public string HEADER { get; set; }
        public string COMPANYNAME { get; set; }
        public string STARTDATE { get; set; }
        public string ENDDATE { get; set; }
        public string DETAIL { get; set; }
    }
}
