//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ProjectImages
    {
        public int ID { get; set; }
        public Nullable<int> PROJECTID { get; set; }
        public string IMAGE { get; set; }
    
        public virtual Tbl_Projects Tbl_Projects { get; set; }
    }
}
