//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Projects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Projects()
        {
            this.Tbl_ProjectImages = new HashSet<Tbl_ProjectImages>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public string HEADER { get; set; }
        public string IMAGE { get; set; }
        public string GITHUB { get; set; }
    
        public virtual Tbl_ProjectCategories Tbl_ProjectCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ProjectImages> Tbl_ProjectImages { get; set; }
    }
}
