//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace my_website.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Accounts
    {
        public int ID { get; set; }
        public Nullable<int> ICONID { get; set; }
        public string LINK { get; set; }
        public string NAME { get; set; }
    
        public virtual Tbl_AccountIcons Tbl_AccountIcons { get; set; }
    }
}
